#        _         _ _
#  _   _| |    ___(_) | __ _  ___
# | | | | |   / _ \ | |/ _` |/ _ \
# | |_| | |__|  __/ | | (_| | (_) |
#  \__, |_____\___|_|_|\__,_|\___/
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Ativar a troca do sistema de chat quando estiver no mohist
# compatível apenas com: UltimateChat, nChat e Legendchat
mohist-chat: false

# Sistemas gerais do plugin
general:
  # Tempo padrão para começar o leilão
  default-time: 1800
  # Quantia máxima de leilões simultâneos que o servidor pode ter
  # deixe 0 para ser infinito
  max-auctions: 10
  # Quantia máxima de leilões simultâneos que o jogador pode fazer
  # deixe 0 para ser infinito
  player-max-auctions: 1
  # Taxa que o leiloador irá pagar sobre o lance vencedor
  # em porcentagem
  auction-tax: 10.0
  # Tempo que irá acrescentar quando um lance maior que um já existente for computado
  # em segundos
  bid-sum-time: 30
  # Tempo mínimo para iniciar um leilão
  # em segundos
  min-time: 900
  # Tempo máximo para iniciar um leilão
  # em segundos
  max-time: 21600

# Sistema de blacklist
black-list:
  # Materiais que estarão na black-list
  materials: [ 'STONE', 'LOG:0' ]
  # NBTTags que estarão na black-list
  nbt-tags: []

# Sistema de whitelist
white-list:
  # Ativar a whitelist
  enabled: false
  # Materiais que estarão na white-list
  materials: [ 'LOG:1', 'TRIPWIRE_HOOK' ]

# Sistema de npc
npc:
  skin: 'Pitombaa'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lLEILÃO'
      - '&7Faça o comércio rápido dos itens!'
      - '[item]EMERALD'